global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "bank-core"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          app: "bank-core-api"
          env: "development"

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
        labels:
          app: "container-metrics"
          env: "development"
